# Generated by Django 5.1.2 on 2025-04-07 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_data", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviews",
            old_name="review_date",
            new_name="created_at",
        ),
    ]
