# Generated by Django 5.2 on 2025-05-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="readinglist",
            name="author_name",
            field=models.CharField(default="Unknown", max_length=256),
            preserve_default=False,
        ),
    ]
