# Generated by Django 5.1.2 on 2025-02-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_data", "0002_readinglist_user_alter_readinglist_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviews",
            old_name="author",
            new_name="reviewer",
        ),
        migrations.AddField(
            model_name="reviews",
            name="book_id",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
