# Generated by Django 5.1.2 on 2025-02-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_data", "0003_rename_author_reviews_reviewer_reviews_book_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="data_time",
        ),
        migrations.AddField(
            model_name="reviews",
            name="review_date",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
