# Generated by Django 5.1.2 on 2025-02-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_data", "0005_rename_author_readinglist_book_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="readinglist",
            name="cover_id",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
