# Generated by Django 5.1.2 on 2025-02-25 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_data", "0006_readinglist_cover_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="comments",
            name="review",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="book_data.reviews",
            ),
            preserve_default=False,
        ),
    ]
