# Generated by Django 5.1.2 on 2025-02-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_data", "0007_comments_review"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comments",
            old_name="review",
            new_name="reviews",
        ),
        migrations.AlterField(
            model_name="comments",
            name="data_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
