# Generated by Django 5.1.2 on 2025-02-26 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book_data", "0008_rename_review_comments_reviews_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="title",
        ),
    ]
