# Generated by Django 5.1.2 on 2025-02-27 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_data", "0009_remove_reviews_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="cover_id",
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
