# Generated by Django 5.1.2 on 2025-02-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_data", "0011_alter_reviews_cover_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="cover_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
