# Generated by Django 5.1.2 on 2025-02-27 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_data", "0012_alter_reviews_cover_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="cover_id",
            field=models.CharField(max_length=50),
        ),
    ]
