# Generated by Django 5.1.2 on 2025-02-27 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_data", "0013_alter_reviews_cover_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="book_title",
            field=models.CharField(default=None, max_length=120),
            preserve_default=False,
        ),
    ]
