# Generated by Django 5.1.2 on 2025-02-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book_data", "0014_reviews_book_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="readinglist",
            name="cover_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
